// <auto-generated />
using System;
using AltenShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AltenShop.Migrations
{
    [DbContext(typeof(DataDBContext))]
    partial class DataDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AltenShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Category = "Accessories",
                            Code = "f230fh0g3",
                            Description = "Product Description",
                            Image = "bamboo-watch.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Bamboo Watch",
                            Price = 65,
                            Quantity = 24,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1001,
                            Category = "Accessories",
                            Code = "nvklal433",
                            Description = "Product Description",
                            Image = "black-watch.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Black Watch",
                            Price = 72,
                            Quantity = 61,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1002,
                            Category = "Fitness",
                            Code = "zz21cz3c1",
                            Description = "Product Description",
                            Image = "blue-band.jpg",
                            InventoryStatus = "LOWSTOCK",
                            Name = "Blue Band",
                            Price = 79,
                            Quantity = 2,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1003,
                            Category = "Clothing",
                            Code = "244wgerg2",
                            Description = "Product Description",
                            Image = "blue-t-shirt.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Blue T-Shirt",
                            Price = 29,
                            Quantity = 25,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1004,
                            Category = "Accessories",
                            Code = "h456wer53",
                            Description = "Product Description",
                            Image = "bracelet.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Bracelet",
                            Price = 15,
                            Quantity = 73,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1005,
                            Category = "Accessories",
                            Code = "av2231fwg",
                            Description = "Product Description",
                            Image = "brown-purse.jpg",
                            InventoryStatus = "OUTOFSTOCK",
                            Name = "Brown Purse",
                            Price = 120,
                            Quantity = 0,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1006,
                            Category = "Accessories",
                            Code = "bib36pfvm",
                            Description = "Product Description",
                            Image = "chakra-bracelet.jpg",
                            InventoryStatus = "LOWSTOCK",
                            Name = "Chakra Bracelet",
                            Price = 32,
                            Quantity = 5,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1007,
                            Category = "Accessories",
                            Code = "mbvjkgip5",
                            Description = "Product Description",
                            Image = "galaxy-earrings.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Galaxy Earrings",
                            Price = 34,
                            Quantity = 23,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1008,
                            Category = "Electronics",
                            Code = "vbb124btr",
                            Description = "Product Description",
                            Image = "game-controller.jpg",
                            InventoryStatus = "LOWSTOCK",
                            Name = "Game Controller",
                            Price = 99,
                            Quantity = 2,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1009,
                            Category = "Electronics",
                            Code = "cm230f032",
                            Description = "Product Description",
                            Image = "gaming-set.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Gaming Set",
                            Price = 299,
                            Quantity = 63,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1010,
                            Category = "Accessories",
                            Code = "plb34234v",
                            Description = "Product Description",
                            Image = "gold-phone-case.jpg",
                            InventoryStatus = "OUTOFSTOCK",
                            Name = "Gold Phone Case",
                            Price = 24,
                            Quantity = 0,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1011,
                            Category = "Electronics",
                            Code = "4920nnc2d",
                            Description = "Product Description",
                            Image = "green-earbuds.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Green Earbuds",
                            Price = 89,
                            Quantity = 23,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1012,
                            Category = "Clothing",
                            Code = "250vm23cc",
                            Description = "Product Description",
                            Image = "green-t-shirt.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Green T-Shirt",
                            Price = 49,
                            Quantity = 74,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1013,
                            Category = "Clothing",
                            Code = "fldsmn31b",
                            Description = "Product Description",
                            Image = "grey-t-shirt.jpg",
                            InventoryStatus = "OUTOFSTOCK",
                            Name = "Grey T-Shirt",
                            Price = 48,
                            Quantity = 0,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1014,
                            Category = "Electronics",
                            Code = "waas1x2as",
                            Description = "Product Description",
                            Image = "headphones.jpg",
                            InventoryStatus = "LOWSTOCK",
                            Name = "Headphones",
                            Price = 175,
                            Quantity = 8,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1015,
                            Category = "Clothing",
                            Code = "vb34btbg5",
                            Description = "Product Description",
                            Image = "light-green-t-shirt.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Light Green T-Shirt",
                            Price = 49,
                            Quantity = 34,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1016,
                            Category = "Fitness",
                            Code = "k8l6j58jl",
                            Description = "Product Description",
                            Image = "lime-band.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Lime Band",
                            Price = 79,
                            Quantity = 12,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1017,
                            Category = "Clothing",
                            Code = "v435nn85n",
                            Description = "Product Description",
                            Image = "mini-speakers.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Mini Speakers",
                            Price = 85,
                            Quantity = 42,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1018,
                            Category = "Accessories",
                            Code = "09zx9c0zc",
                            Description = "Product Description",
                            Image = "painted-phone-case.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Painted Phone Case",
                            Price = 56,
                            Quantity = 41,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1019,
                            Category = "Fitness",
                            Code = "mnb5mb2m5",
                            Description = "Product Description",
                            Image = "pink-band.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Pink Band",
                            Price = 79,
                            Quantity = 63,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1020,
                            Category = "Accessories",
                            Code = "r23fwf2w3",
                            Description = "Product Description",
                            Image = "pink-purse.jpg",
                            InventoryStatus = "OUTOFSTOCK",
                            Name = "Pink Purse",
                            Price = 110,
                            Quantity = 0,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1021,
                            Category = "Fitness",
                            Code = "pxpzczo23",
                            Description = "Product Description",
                            Image = "purple-band.jpg",
                            InventoryStatus = "LOWSTOCK",
                            Name = "Purple Band",
                            Price = 79,
                            Quantity = 6,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1022,
                            Category = "Accessories",
                            Code = "2c42cb5cb",
                            Description = "Product Description",
                            Image = "purple-gemstone-necklace.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Purple Gemstone Necklace",
                            Price = 45,
                            Quantity = 62,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1023,
                            Category = "Clothing",
                            Code = "5k43kkk23",
                            Description = "Product Description",
                            Image = "purple-t-shirt.jpg",
                            InventoryStatus = "LOWSTOCK",
                            Name = "Purple T-Shirt",
                            Price = 49,
                            Quantity = 2,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1024,
                            Category = "Clothing",
                            Code = "lm2tny2k4",
                            Description = "Product Description",
                            Image = "shoes.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Shoes",
                            Price = 64,
                            Quantity = 0,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1025,
                            Category = "Clothing",
                            Code = "nbm5mv45n",
                            Description = "Product Description",
                            Image = "sneakers.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Sneakers",
                            Price = 78,
                            Quantity = 52,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1026,
                            Category = "Clothing",
                            Code = "zx23zc42c",
                            Description = "Product Description",
                            Image = "teal-t-shirt.jpg",
                            InventoryStatus = "LOWSTOCK",
                            Name = "Teal T-Shirt",
                            Price = 49,
                            Quantity = 3,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1027,
                            Category = "Electronics",
                            Code = "acvx872gc",
                            Description = "Product Description",
                            Image = "yellow-earbuds.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Yellow Earbuds",
                            Price = 89,
                            Quantity = 35,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1028,
                            Category = "Fitness",
                            Code = "tx125ck42",
                            Description = "Product Description",
                            Image = "yoga-mat.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Yoga Mat",
                            Price = 20,
                            Quantity = 15,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1029,
                            Category = "Fitness",
                            Code = "gwuby345v",
                            Description = "Product Description",
                            Image = "yoga-set.jpg",
                            InventoryStatus = "INSTOCK",
                            Name = "Yoga Set",
                            Price = 20,
                            Quantity = 25,
                            Rating = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
